Update dependencies and fetch weather data

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,7 @@ jobs:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0 # Fetch all history for all branches and tags
+        name: Checkout Repository
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
@@ -19,7 +20,10 @@ jobs:
           node-version: "v21.1.0" # Specify the Node.js version
 
       - name: Install Dependencies
-        run: npm install
+        run: |
+          echo "Installing dependencies..."
+          npm install
+          echo "Dependencies installed."
 
       - name: Fetch Weather Data
         working-directory: ./ # Set the working directory to the root of the repository
@@ -28,20 +32,52 @@ jobs:
         run: |
           echo "Fetching Weather Data..."
           node fetchWeather.js
+          echo "Weather Data Fetched."
+
+      - name: Debugging Information Before Git Operations
+        run: |
+          echo "Current Directory:"
+          pwd
+          echo "List Files:"
+          ls -la
+          echo "Git Status Before Changes:"
+          git status
 
       - name: Commit and push if changed
         run: |
           echo "Configuring Git..."
           git config --global user.email "hyates1@gmail.com"
           git config --global user.name "Harry-Yates"
+          echo "Git Configuration Set."
+
           echo "Fetching latest from main branch..."
           git fetch origin main || (echo "Failed to fetch from main" && exit 1)
+          echo "Latest fetched."
+
           echo "Resetting to the latest commit..."
           git reset --hard FETCH_HEAD || (echo "Failed to reset to FETCH_HEAD" && exit 1)
+          echo "Reset to latest commit."
+
           echo "Checking for changes in README.md..."
           git add README.md || (echo "Failed to add README.md" && exit 1)
+          echo "README.md added."
+
+          echo "Git Status After Changes:"
           git status
-          git diff-index --quiet HEAD || (echo "Changes detected, committing..." && git commit -m "Update Weather" || (echo "Failed to commit changes" and exit 1))
+
+          echo "Git Diff:"
+          git diff
+
+          git diff-index --quiet HEAD || (echo "Changes detected, committing..." && git commit -m "Update Weather" || (echo "Failed to commit changes" && exit 1))
+          echo "Changes Committed."
+
           echo "Pushing changes to main branch..."
           git push origin main || (echo "Push failed" && exit 1)
-          echo "Push successful"
+          echo "Push successful."
+
+      - name: Debugging Information After Git Operations
+        run: |
+          echo "Git Status After Push:"
+          git status
+          echo "Git Log:"
+          git log -n 5
