Update Weather

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,13 +3,15 @@ name: Update Weather
 on:
   schedule:
     - cron: "0 * * * *" # Runs every hour
-  workflow_dispatch: # Add this line for manual trigger
+  workflow_dispatch: # Manual trigger
 
 jobs:
   update-weather:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0 # Fetch all history for all branches and tags
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
@@ -20,13 +22,25 @@ jobs:
         run: npm install
 
       - name: Fetch Weather Data
+        env:
+          OPEN_WEATHER: ${{ secrets.OPEN_WEATHER }} # Use the secret as an environment variable
         run: |
-          node fetchWeather.js # Run the JavaScript script
+          echo "Fetching Weather Data..."
+          node fetchWeather.js
 
       - name: Commit and push if changed
         run: |
+          echo "Configuring Git..."
           git config --global user.email "hyates1@gmail.com"
           git config --global user.name "Harry-Yates"
-          git pull --rebase
-          git diff --quiet || git commit -am "Update Weather"
-          git push
+          echo "Fetching latest from main branch..."
+          git fetch origin main || (echo "Failed to fetch from main" && exit 1)
+          echo "Resetting to the latest commit..."
+          git reset --hard FETCH_HEAD || (echo "Failed to reset to FETCH_HEAD" && exit 1)
+          echo "Checking for changes in README.md..."
+          git add README.md || (echo "Failed to add README.md" && exit 1)
+          git status
+          git diff-index --quiet HEAD || (echo "Changes detected, committing..." && git commit -m "Update Weather" || (echo "Failed to commit changes" && exit 1))
+          echo "Pushing changes to main branch..."
+          git push origin main || (echo "Push failed" && exit 1)
+          echo "Push successful"
