Updates user name and email

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,8 +48,8 @@ jobs:
           echo "Configuring Git..."
           # git config --global user.email "hyates1@gmail.com"
           # git config --global user.name "Harry-Yates"
-            git config --global user.name "Weatherman"
-            git config --global user.email "weatherman@weatherman.com"
+            git config --global user.name "Aeolus"
+            git config --global user.email "Aeolus@Aeolus.com"
           echo "Git Configuration Set."
 
           echo "Fetching latest from main branch..."
@@ -66,7 +66,7 @@ jobs:
           echo "Git Diff:"
           git diff
 
-          git diff-index --quiet HEAD || (echo "Changes detected, committing..." && git commit -m "Update Weather" || (echo "Failed to commit changes" && exit 1))
+          git diff-index --quiet HEAD || (echo "Changes detected, committing..." && git commit -m "Shifts the Weather" || (echo "Failed to commit changes" && exit 1))
           echo "Changes Committed."
 
           echo "Pushing changes to main branch..."
